import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("wali").del();

  // Inserts seed entries
  await knex("wali").insert([
    {
      id: "W001",
      sekolah_id: "S001",
      nik: "3201010000010001",
      nama_lengkap: "Budi Santoso",
      nama_panggilan: "Budi",
      gender: "L",
      tempat_lahir: "Bandung",
      tanggal_lahir: "1980-05-12",
      alamat_tinggal: "Jl. Ahmad Yani No. 45, Bandung",
      no_telepon: "081234567890",
      email: "budi.santoso@example.com",
      pendidikan_terakhir: "S1",
      pekerjaan: "Wiraswasta",
      hubungan: "Ayah",
      nama_ibu: "Siti Aminah",
      pendidikan_terakhir_ibu: "SMA",
      pekerjaan_ibu: "Ibu Rumah Tangga",
      nama_bapak: "Sukirman",
      pendidikan_terakhir_bapak: "SMP",
      pekerjaan_bapak: "Petani",
      deleted: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "W002",
      sekolah_id: "S002",
      nik: "3201010000020002",
      nama_lengkap: "Sri Wahyuni",
      nama_panggilan: "Yuni",
      gender: "P",
      tempat_lahir: "Jakarta",
      tanggal_lahir: "1982-08-20",
      alamat_tinggal: "Jl. Sudirman No. 10, Jakarta",
      no_telepon: "081298765432",
      email: "sri.wahyuni@example.com",
      pendidikan_terakhir: "D3",
      pekerjaan: "Pegawai Negeri",
      hubungan: "Ibu",
      nama_ibu: "Kartini",
      pendidikan_terakhir_ibu: "SMA",
      pekerjaan_ibu: "Ibu Rumah Tangga",
      nama_bapak: "Suparman",
      pendidikan_terakhir_bapak: "SMP",
      pekerjaan_bapak: "Buruh",
      deleted: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "W003",
      sekolah_id: "S003",
      nik: "3201010000030003",
      nama_lengkap: "Andi Wijaya",
      nama_panggilan: "Andi",
      gender: "L",
      tempat_lahir: "Semarang",
      tanggal_lahir: "1985-11-05",
      alamat_tinggal: "Jl. Pemuda No. 20, Semarang",
      no_telepon: "081356789012",
      email: "andi.wijaya@example.com",
      pendidikan_terakhir: "S2",
      pekerjaan: "Dosen",
      hubungan: "Ayah",
      nama_ibu: "Rini Astuti",
      pendidikan_terakhir_ibu: "S1",
      pekerjaan_ibu: "Guru",
      nama_bapak: "Sudirman",
      pendidikan_terakhir_bapak: "SMA",
      pekerjaan_bapak: "Wiraswasta",
      deleted: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ]);
}
